INSERT INTO USER (USERNAME, PASSWORD, ENABLED, LASTPASSWORDRESETTIME) VALUES ('admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1, PARSEDATETIME('2018-07-21', 'yyyy-MM-dd'));
INSERT INTO USER (USERNAME, PASSWORD, ENABLED, LASTPASSWORDRESETTIME) VALUES ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1, PARSEDATETIME('2018-07-21','yyyy-MM-dd'));
INSERT INTO USER (USERNAME, PASSWORD, ENABLED, LASTPASSWORDRESETTIME) VALUES ('disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 0, PARSEDATETIME('2018-07-21','yyyy-MM-dd'));

INSERT INTO AUTHORITY (NAME) VALUES ('ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('USER');

INSERT INTO USER_AUTHORITY (USERNAME, AUTHORITY) VALUES ('admin', 'ADMIN');
INSERT INTO USER_AUTHORITY (USERNAME, AUTHORITY) VALUES ('admin', 'USER');
INSERT INTO USER_AUTHORITY (USERNAME, AUTHORITY) VALUES ('user', 'USER');
INSERT INTO USER_AUTHORITY (USERNAME, AUTHORITY) VALUES ('disabled', 'USER');
